### ISSUE TITLE
Does not work if there is no jQuery on the page

### ISSUE THREAD

**Issue by georgy7** [olore/watir-jquery#2]
```
[remote server] https://example.com/ line 68 > Function:1:in `anonymous': jQuery is not defined (Selenium::WebDriver::Error::JavascriptError)
        from [remote server] https://example.com/:68:in `handleEvaluateEvent'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:339:in `executeScript'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:193:in `execute_script'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/watir-webdriver-0.7.0/lib/watir-webdriver/browser.rb:255:in `execute_script'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/watir-jquery-0.0.2/lib/watir-jquery.rb:10:in `jquery'
```

**Comment by georgy7** [comment]
Doesn't matter. Nokogiri is ok.
